### ISSUE TITLE
"Count" column shows 0 for small tables

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/soddi#12]
If your table's row count is smaller than the batch size setting, it'll show 0 for "Count" even when rows are successfully imported.

Repro steps:

1. Set the "Batch Size" count higher than the smallest table's rows (the default of 5000 is fine for dba.stackexchange.com's Tags table)
2. Import a relatively small site, like dba.stackexchange.com
3. When it finishes, the "Count" column shows 0 for Tags. I'm guessing the Count is only updated each time a batch finishes. (Which is fine, we don't need an exact row count.)

Just adding this in Issues so we know we have a known issue.

**Comment by abrobston** [comment]
Done.  I went ahead and displayed a final row count for each table as doing so in all cases is easier than determining whether a table is "small" before doing so.
