### ISSUE TITLE
xcopy flavour of the binaries

### ISSUE THREAD

**Issue by chrgraefe** [BrentOzarULTD/soddi#14]
Please provide a zip only variant of the binaries. :-)

**Comment by BrentOzar** [comment]
Why?

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by chrgraefe** [comment]
Just simple to deploy for a short deployment process. Nothing to install just copy and run

**Comment by BrentOzar** [comment]
Gotcha. Speed of deployment isn't really a primary concern for this project, so I'm going to close it. If you want to work on it, though, you're welcome to, and then submit a pull request.
