### ISSUE TITLE
Table Creation Ignoring DEFAULT FileGroup

### ISSUE THREAD

**Issue by imajaydwivedi** [BrentOzarULTD/soddi#18]
Recent dump 122018 is of large size. So to make XML data import quick, I added multiple Data Files in New filegroup 'DATA' & marked it as Default. Still, the tool SODDI created all the tables in PRIMARY filegroup.

Could it be modified to create tables in DEFAULT filegroup rather then on PRIMARY.

**Comment by BrentOzar** [comment]
You can achieve the same result by just adding multiple data files to the primary data file group. That's how I did this: https://www.brentozar.com/go/querystack

We're not doing active development on this app, but the beauty of open source is that you can make the change yourself and contribute the code back if you want.
