### ISSUE TITLE
Query TimeOut while Importing Data of Posts.XML after 1 Hour

### ISSUE THREAD

**Issue by imajaydwivedi** [BrentOzarULTD/soddi#19]
I am using latest version of SODDI (1.5) with latest StackOverflow dumps (122018). Import activity fails everytime for Posts.XML dump file after an approx execution time of 1 hour. Other other dumps, it successfully imports. I tried switching various values of BatchSize but it did not help.

I have verified, remote query timeout is set to 0 on SQL Server side.

**Comment by BrentOzar** [comment]
Works fine here. Try checking your error log, disk space, etc.

You can also just download the database: https://www.brentozar.com/go/querystack
