### ISSUE TITLE
Update Help/About to reflect current license, downloads

### ISSUE THREAD

**Issue by BrentOzar** [BrentOzarULTD/soddi#9]
In the app, if you click Help/About, everything's outdated. (Sky passed away, his web site is no longer available, Jeremiah took his mirror of the project down, and it's probably not .NET 3.5 SP1.) Let's just point people to the Github repo for now to read the readme there:

https://github.com/BrentOzarULTD/soddi

**Comment by abrobston** [comment]
Done.
